# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motorista', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(editable=False)),
                ('duracao', models.DurationField()),
                ('path_foto', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField()),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carregamentos.Caminhao')),
            ],
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='frente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carregamentos.Frente'),
        ),
    ]
