# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0002_auto_20160518_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='id_caminhao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
