# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:55
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0002_carregamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carregamento',
            name='photo',
        ),
        migrations.AddField(
            model_name='carregamento',
            name='picture',
            field=webcam.fields.CameraField(null=True, storage=webcam.storage.CameraStorage(), upload_to=b''),
        ),
    ]
