# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:19
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0003_auto_20160514_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carregamento',
            name='picture',
        ),
        migrations.AddField(
            model_name='carregamento',
            name='photo',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'pictures', verbose_name=b'CameraPictureField'),
        ),
    ]
