# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0003_carregamento_id_caminhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='caminhao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carregamentos.Caminhao'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'carregamentos-photo', verbose_name=b'CameraPictureField'),
        ),
    ]
