# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0003_auto_20160525_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='manifesto',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carregamento',
            name='tiquete',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
