# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0004_auto_20160520_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b'carregamentos-photo'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='photo',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'carregamentos-photo', verbose_name=b'CameraPictureField'),
        ),
    ]
