# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0005_auto_20160520_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caminhao',
            old_name='created_at',
            new_name='data_alteracao',
        ),
        migrations.RenameField(
            model_name='caminhao',
            old_name='updated_at',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='carregamento',
            old_name='created_at',
            new_name='data_alteracao',
        ),
        migrations.RenameField(
            model_name='carregamento',
            old_name='updated_at',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='frente',
            old_name='created_at',
            new_name='data_alteracao',
        ),
        migrations.RenameField(
            model_name='frente',
            old_name='updated_at',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=b'carregamentos-photo'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='photo',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'carregamentos-photo', verbose_name=b'foto'),
        ),
    ]
