# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:33
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0005_caminhao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='foto',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'media/caminhao', verbose_name=b'foto'),
        ),
    ]
