# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0005_remove_carregamento_path_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='duracao',
            field=models.DurationField(editable=False),
        ),
    ]
