# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0008_auto_20160601_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='caminhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carregamentos.Caminhao'),
        ),
    ]
