# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0013_auto_20160602_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
