# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0014_auto_20160602_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='tiquete',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name=b'Tiquete Anterior'),
        ),
    ]
