# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0015_auto_20160603_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caminhao',
            old_name='profundidade',
            new_name='comprimento',
        ),
    ]
