# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('carregamentos', '0018_auto_20160605_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhao',
            name='photo',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'media/caminhao', verbose_name=b'foto'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b'media'),
        ),
    ]
