branch-defaults:
  default:
    environment: bbbcaminhao-dev
    group_suffix: null
global:
  application_name: bbbcaminhao
  default_ec2_keyname: bbbcaminhao
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
